import type { Language } from "./api/types";

/** Libellés d'interface (chrome UI) traduits dans les 4 langues d'affichage.
 * Séparés du contenu métier (data/ifc_reference.json) qui est traduit côté
 * backend ; ce fichier ne couvre que le texte fixe des composants React. */
export const UI_STRINGS: Record<Language, Record<string, string>> = {
  fr: {
    availableTypesFor: "Types prédéfinis (PredefinedType) disponibles pour",
    refineHint: "Précisez votre recherche avec l'un de ces types (ex. «",
    refineHintEnd: "») ou consultez la",
    detailSheet: "fiche détaillée",
    forCompleteList: "pour la liste complète avec synonymes.",
    whichPset: "Quel Pset utiliser ?",
    matchedTerm: "Terme correspondant",
    score: "score",
    definition: "Définition",
    originalEnglish: "Version originale anglaise (buildingSMART)",
    hierarchyPosition: "Position dans la hiérarchie",
    parentClass: "Classe parente",
    childClasses: "Classes filles référencées",
    predefinedTypesTitle: "Types prédéfinis (PredefinedType)",
    colValue: "Valeur",
    colSince: "Depuis",
    colDescription: "Description",
    colSynonyms: "Synonymes",
    newIn43: "Nouveau en 4.3",
    deprecated: "Déprécié",
    versionHistory: "Historique de version",
    introducedIn: "Introduit en IFC",
    currentVersion: "version courante IFC",
    deprecatedSince: "Déprécié depuis IFC",
  },
  en: {
    availableTypesFor: "Available PredefinedType values for",
    refineHint: "Refine your search with one of these types (e.g. «",
    refineHintEnd: "») or see the",
    detailSheet: "detail sheet",
    forCompleteList: "for the complete list with synonyms.",
    whichPset: "Which Pset should I use?",
    matchedTerm: "Matched term",
    score: "score",
    definition: "Definition",
    originalEnglish: "Original English version (buildingSMART)",
    hierarchyPosition: "Position in the hierarchy",
    parentClass: "Parent class",
    childClasses: "Referenced child classes",
    predefinedTypesTitle: "PredefinedType values",
    colValue: "Value",
    colSince: "Since",
    colDescription: "Description",
    colSynonyms: "Synonyms",
    newIn43: "New in 4.3",
    deprecated: "Deprecated",
    versionHistory: "Version history",
    introducedIn: "Introduced in IFC",
    currentVersion: "current version IFC",
    deprecatedSince: "Deprecated since IFC",
  },
  it: {
    availableTypesFor: "Valori PredefinedType disponibili per",
    refineHint: "Precisate la ricerca con uno di questi tipi (es. «",
    refineHintEnd: "») oppure consultate la",
    detailSheet: "scheda dettagliata",
    forCompleteList: "per l'elenco completo con i sinonimi.",
    whichPset: "Quale Pset utilizzare?",
    matchedTerm: "Termine corrispondente",
    score: "punteggio",
    definition: "Definizione",
    originalEnglish: "Versione originale inglese (buildingSMART)",
    hierarchyPosition: "Posizione nella gerarchia",
    parentClass: "Classe padre",
    childClasses: "Classi figlie referenziate",
    predefinedTypesTitle: "Valori PredefinedType",
    colValue: "Valore",
    colSince: "Da",
    colDescription: "Descrizione",
    colSynonyms: "Sinonimi",
    newIn43: "Novità 4.3",
    deprecated: "Deprecato",
    versionHistory: "Cronologia versioni",
    introducedIn: "Introdotto in IFC",
    currentVersion: "versione corrente IFC",
    deprecatedSince: "Deprecato dalla IFC",
  },
  de: {
    availableTypesFor: "Verfügbare PredefinedType-Werte für",
    refineHint: "Präzisieren Sie Ihre Suche mit einem dieser Typen (z. B. «",
    refineHintEnd: "») oder sehen Sie sich das",
    detailSheet: "Detailblatt",
    forCompleteList: "für die vollständige Liste mit Synonymen an.",
    whichPset: "Welches Pset verwenden?",
    matchedTerm: "Gefundener Begriff",
    score: "Punktzahl",
    definition: "Definition",
    originalEnglish: "Englische Originalversion (buildingSMART)",
    hierarchyPosition: "Position in der Hierarchie",
    parentClass: "Übergeordnete Klasse",
    childClasses: "Referenzierte Unterklassen",
    predefinedTypesTitle: "PredefinedType-Werte",
    colValue: "Wert",
    colSince: "Seit",
    colDescription: "Beschreibung",
    colSynonyms: "Synonyme",
    newIn43: "Neu in 4.3",
    deprecated: "Veraltet",
    versionHistory: "Versionsverlauf",
    introducedIn: "Eingeführt in IFC",
    currentVersion: "aktuelle Version IFC",
    deprecatedSince: "Veraltet seit IFC",
  },
};
